Remove unnecessary keyword argument
Instantiating our own exceptions doesn't require 'message' keyword
argument, doing it causes the following exception:

Traceback (most recent call last):
  File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxyadmin/internal.py", line 88, in command
    data = file_handle.read().splitlines()
  File "/opt/blue-python/3.4/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./hap-requests.py", line 115, in <module>
    main()
  File "./hap-requests.py", line 82, in main
    backend = hap.backend(arguments['NAME'])
  File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxyadmin/haproxy.py", line 685, in backend
    _backend = self.backends(name)
  File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxyadmin/haproxy.py", line 666, in backends
    for backend in hap_process.backends(name):
  File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxyadmin/internal.py", line 213, in backends
    backends = self.backends_stats()
  File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxyadmin/internal.py", line 183, in backends_stats
    return self.stats(iid, obj_type=2)['backends']
  File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxyadmin/internal.py", line 165, in stats
    full_output=True)
  File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxyadmin/internal.py", line 94, in command
    socket_file=self.socket_file)
TypeError: __init__() got an unexpected keyword argument 'message'